# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            open-fsharp
tagline:          'A conference to learn, create and connect with F# and its Community.'
description:      'A conference to learn, create and connect with F# and its Community.'
url:              https://open-fsharp.github.io/
baseurl:          ""

author:
  name:           'Open Fsharp'
  url:            https://twitter.com/openfsharp

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/open-fsharp/open-fsharp.github.io
